import type { Locale, Messages } from "./types";

const en: Messages = {
  navAssets:"Assets",navExposure:"Service Exposure",navCompare:"Compare",navRemediation:"Remediation",
  "toolbox.eyebrow":"Governance toolbox","toolbox.assets":"Asset Inventory","toolbox.assetsDescription":"Observed assets, category guesses, and local network context.",
  "toolbox.exposure":"Service Exposure Matrix","toolbox.exposureDescription":"Governance view of observed services, mDNS announcements, and Web/TLS baselines.",
  "toolbox.compare":"Snapshot Compare","toolbox.compareDescription":"Changes observed since the previous local audit.",
  "toolbox.remediation":"Remediation Tracking","toolbox.remediationDescription":"Local ownership, priority, justification, and status records.",
  "toolbox.owner":"Owner","toolbox.dueDate":"Due date","toolbox.status":"Status","toolbox.priority":"Priority","toolbox.businessJustification":"Business justification","toolbox.notes":"Notes","toolbox.saveRemediation":"Save remediation tracker","toolbox.remediationSaved":"Remediation tracker saved locally.","toolbox.noRemediation":"No remediation records are available.","toolbox.remediationLimit":"Tracking updates local governance records only. No remediation command is executed.","toolbox.statusOpen":"Open","toolbox.statusAccepted":"Accepted risk","toolbox.statusProgress":"In progress","toolbox.statusRemediated":"Remediated","toolbox.priorityRoutine":"Routine",
  "toolbox.observationLimit":"These are point-in-time governance observations. No service login or configuration change is performed.",
  "toolbox.file.assetInventorySummary":"Asset inventory summary","toolbox.file.assetInventory":"Asset inventory",
  "toolbox.file.localNetworkConfig":"Local network configuration","toolbox.file.serviceExposureSummary":"Service exposure summary",
  "toolbox.file.serviceExposureMatrix":"Service exposure matrix","toolbox.file.mdnsServices":"Bonjour / mDNS observations",
  "toolbox.file.webBaseline":"Web baseline","toolbox.file.tlsCertificates":"TLS certificates",
  "toolbox.file.snapshotDiff":"Snapshot difference","toolbox.file.governanceSummary":"Governance summary",
  "toolbox.file.remediationTracking":"Remediation tracker","toolbox.file.remediationRoadmap":"Remediation roadmap",
  "step.localNetworkConfig":"Local network configuration","step.localNetworkConfigDescription":"Observe current interface, gateway, DNS, DHCP, and VPN route context.",
  "step.mdnsObservation":"Bonjour / mDNS observation","step.mdnsObservationDescription":"Observe local service announcements for a fixed short duration.",
  "step.webTlsBaseline":"Web and TLS baseline","step.webTlsBaselineDescription":"Observe basic headers and certificates on already-discovered Web services.",
  "step.enhancedReport":"Enhanced governance report","step.enhancedReportDescription":"Build inventory, exposure, history, remediation, and summary outputs.",
};

const overlays: Partial<Record<Locale, Messages>> = {
  "zh-CN": {navAssets:"资产",navExposure:"服务暴露",navCompare:"对比",navRemediation:"整改","toolbox.eyebrow":"治理工具箱","toolbox.assets":"资产清单","toolbox.assetsDescription":"查看已观察资产、设备类别推测和本地网络环境。","toolbox.exposure":"服务暴露矩阵","toolbox.exposureDescription":"查看已观察服务、mDNS 公告和 Web/TLS 基线。","toolbox.compare":"审计快照对比","toolbox.compareDescription":"查看与上一次本地审计相比的变化。","toolbox.remediation":"整改跟踪","toolbox.remediationDescription":"本地记录负责人、优先级、业务理由和状态。","toolbox.observationLimit":"这些是时点治理观察，不登录服务，也不修改配置。","toolbox.file.assetInventorySummary":"资产清单摘要","toolbox.file.assetInventory":"资产清单","toolbox.file.localNetworkConfig":"本地网络配置","toolbox.file.serviceExposureSummary":"服务暴露摘要","toolbox.file.serviceExposureMatrix":"服务暴露矩阵","toolbox.file.mdnsServices":"Bonjour / mDNS 观察","toolbox.file.webBaseline":"Web 基线","toolbox.file.tlsCertificates":"TLS 证书","toolbox.file.snapshotDiff":"快照差异","toolbox.file.governanceSummary":"治理摘要","toolbox.file.remediationTracking":"整改跟踪台账","toolbox.file.remediationRoadmap":"整改路线图","step.localNetworkConfig":"本地网络配置","step.localNetworkConfigDescription":"观察当前接口、网关、DNS、DHCP 和 VPN 路由环境。","step.mdnsObservation":"Bonjour / mDNS 观察","step.mdnsObservationDescription":"在固定短时间内观察本地服务公告。","step.webTlsBaseline":"Web 与 TLS 基线","step.webTlsBaselineDescription":"观察已发现 Web 服务的基础响应头和证书。","step.enhancedReport":"增强治理报告","step.enhancedReportDescription":"生成资产、暴露、历史、整改和摘要输出。"},
  "zh-TW": {navAssets:"資產",navExposure:"服務暴露",navCompare:"比較",navRemediation:"修正","toolbox.eyebrow":"治理工具箱","toolbox.assets":"資產清單","toolbox.assetsDescription":"檢視已觀察資產、裝置類別推測及本機網路環境。","toolbox.exposure":"服務暴露矩陣","toolbox.exposureDescription":"檢視已觀察服務、mDNS 公告及 Web/TLS 基線。","toolbox.compare":"稽核快照比較","toolbox.compareDescription":"檢視與上一次本機稽核相比的變化。","toolbox.remediation":"修正追蹤","toolbox.remediationDescription":"本機記錄負責人、優先順序、業務理由及狀態。","toolbox.observationLimit":"這些是時點治理觀察，不登入服務，也不修改設定。","toolbox.file.assetInventorySummary":"資產清單摘要","toolbox.file.assetInventory":"資產清單","toolbox.file.localNetworkConfig":"本機網路設定","toolbox.file.serviceExposureSummary":"服務暴露摘要","toolbox.file.serviceExposureMatrix":"服務暴露矩陣","toolbox.file.mdnsServices":"Bonjour / mDNS 觀察","toolbox.file.webBaseline":"Web 基線","toolbox.file.tlsCertificates":"TLS 憑證","toolbox.file.snapshotDiff":"快照差異","toolbox.file.governanceSummary":"治理摘要","toolbox.file.remediationTracking":"修正追蹤台帳","toolbox.file.remediationRoadmap":"修正路線圖","step.localNetworkConfig":"本機網路設定","step.localNetworkConfigDescription":"觀察目前介面、閘道、DNS、DHCP 及 VPN 路由環境。","step.mdnsObservation":"Bonjour / mDNS 觀察","step.mdnsObservationDescription":"在固定短時間內觀察本機服務公告。","step.webTlsBaseline":"Web 與 TLS 基線","step.webTlsBaselineDescription":"觀察已發現 Web 服務的基礎標頭及憑證。","step.enhancedReport":"增強治理報告","step.enhancedReportDescription":"生成資產、暴露、歷史、修正及摘要輸出。"},
  ja: {navAssets:"資産",navExposure:"サービス公開",navCompare:"比較",navRemediation:"是正管理","toolbox.eyebrow":"ガバナンスツールボックス","toolbox.assets":"資産インベントリ","toolbox.assetsDescription":"観測された資産、カテゴリ推定、ローカルネットワーク状況を表示します。","toolbox.exposure":"サービス公開マトリクス","toolbox.exposureDescription":"観測サービス、mDNS 通知、Web/TLS 基準を表示します。","toolbox.compare":"監査スナップショット比較","toolbox.compareDescription":"前回のローカル監査からの変化を表示します。","toolbox.remediation":"是正追跡","toolbox.remediationDescription":"担当者、優先度、業務上の理由、状態をローカルで記録します。","toolbox.observationLimit":"時点ガバナンス観測です。サービスへのログインや設定変更は行いません。","toolbox.file.assetInventorySummary":"資産インベントリ概要","toolbox.file.assetInventory":"資産インベントリ","toolbox.file.localNetworkConfig":"ローカルネットワーク設定","toolbox.file.serviceExposureSummary":"サービス公開概要","toolbox.file.serviceExposureMatrix":"サービス公開マトリクス","toolbox.file.mdnsServices":"Bonjour / mDNS 観測","toolbox.file.webBaseline":"Web 基準","toolbox.file.tlsCertificates":"TLS 証明書","toolbox.file.snapshotDiff":"スナップショット差分","toolbox.file.governanceSummary":"ガバナンス概要","toolbox.file.remediationTracking":"是正追跡台帳","toolbox.file.remediationRoadmap":"是正ロードマップ","step.localNetworkConfig":"ローカルネットワーク設定","step.localNetworkConfigDescription":"現在のインターフェース、ゲートウェイ、DNS、DHCP、VPN 経路を観測します。","step.mdnsObservation":"Bonjour / mDNS 観測","step.mdnsObservationDescription":"固定された短時間だけローカルサービス通知を観測します。","step.webTlsBaseline":"Web / TLS 基準","step.webTlsBaselineDescription":"検出済み Web サービスの基本ヘッダーと証明書を観測します。","step.enhancedReport":"拡張ガバナンスレポート","step.enhancedReportDescription":"資産、公開状況、履歴、是正、概要を生成します。"},
  ko: {navAssets:"자산",navExposure:"서비스 노출",navCompare:"비교",navRemediation:"개선 추적","toolbox.eyebrow":"거버넌스 도구 상자","toolbox.assets":"자산 목록","toolbox.assetsDescription":"관찰된 자산, 범주 추정 및 로컬 네트워크 상황을 표시합니다.","toolbox.exposure":"서비스 노출 매트릭스","toolbox.exposureDescription":"관찰된 서비스, mDNS 알림 및 Web/TLS 기준을 표시합니다.","toolbox.compare":"감사 스냅샷 비교","toolbox.compareDescription":"이전 로컬 감사 이후 변경 사항을 표시합니다.","toolbox.remediation":"개선 추적","toolbox.remediationDescription":"담당자, 우선순위, 업무 근거와 상태를 로컬에 기록합니다.","toolbox.observationLimit":"시점 거버넌스 관찰입니다. 서비스 로그인이나 구성 변경을 수행하지 않습니다.","toolbox.file.assetInventorySummary":"자산 목록 요약","toolbox.file.assetInventory":"자산 목록","toolbox.file.localNetworkConfig":"로컬 네트워크 구성","toolbox.file.serviceExposureSummary":"서비스 노출 요약","toolbox.file.serviceExposureMatrix":"서비스 노출 매트릭스","toolbox.file.mdnsServices":"Bonjour / mDNS 관찰","toolbox.file.webBaseline":"Web 기준","toolbox.file.tlsCertificates":"TLS 인증서","toolbox.file.snapshotDiff":"스냅샷 차이","toolbox.file.governanceSummary":"거버넌스 요약","toolbox.file.remediationTracking":"개선 추적 대장","toolbox.file.remediationRoadmap":"개선 로드맵","step.localNetworkConfig":"로컬 네트워크 구성","step.localNetworkConfigDescription":"현재 인터페이스, 게이트웨이, DNS, DHCP 및 VPN 경로를 관찰합니다.","step.mdnsObservation":"Bonjour / mDNS 관찰","step.mdnsObservationDescription":"고정된 짧은 시간 동안 로컬 서비스 알림을 관찰합니다.","step.webTlsBaseline":"Web 및 TLS 기준","step.webTlsBaselineDescription":"이미 발견된 Web 서비스의 기본 헤더와 인증서를 관찰합니다.","step.enhancedReport":"향상된 거버넌스 보고서","step.enhancedReportDescription":"자산, 노출, 기록, 개선 및 요약 출력을 생성합니다."},
  de:{navAssets:"Assets",navExposure:"Dienstexposition",navCompare:"Vergleich",navRemediation:"Behebung","toolbox.eyebrow":"Governance-Werkzeugkasten","toolbox.assets":"Asset-Inventar","toolbox.assetsDescription":"Beobachtete Assets, Kategorieannahmen und lokaler Netzwerkkontext.","toolbox.exposure":"Dienstexpositionsmatrix","toolbox.exposureDescription":"Beobachtete Dienste, mDNS-Ankündigungen und Web/TLS-Baselines.","toolbox.compare":"Snapshot-Vergleich","toolbox.compareDescription":"Änderungen seit dem vorherigen lokalen Audit.","toolbox.remediation":"Behebungsverfolgung","toolbox.remediationDescription":"Lokale Zuständigkeiten, Prioritäten, Begründungen und Status.","toolbox.observationLimit":"Zeitpunktbezogene Governance-Beobachtungen ohne Dienstanmeldung oder Konfigurationsänderung."},
  fr:{navAssets:"Actifs",navExposure:"Exposition",navCompare:"Comparer",navRemediation:"Correction","toolbox.eyebrow":"Boîte à outils de gouvernance","toolbox.assets":"Inventaire des actifs","toolbox.assetsDescription":"Actifs observés, catégories estimées et contexte réseau local.","toolbox.exposure":"Matrice d’exposition des services","toolbox.exposureDescription":"Services observés, annonces mDNS et références Web/TLS.","toolbox.compare":"Comparaison des instantanés","toolbox.compareDescription":"Changements depuis le précédent audit local.","toolbox.remediation":"Suivi des corrections","toolbox.remediationDescription":"Responsables, priorités, justifications et états locaux.","toolbox.observationLimit":"Observations ponctuelles sans connexion aux services ni modification de configuration."},
  es:{navAssets:"Activos",navExposure:"Exposición",navCompare:"Comparar",navRemediation:"Corrección","toolbox.eyebrow":"Herramientas de gobernanza","toolbox.assets":"Inventario de activos","toolbox.assetsDescription":"Activos observados, categorías estimadas y contexto de red local.","toolbox.exposure":"Matriz de exposición de servicios","toolbox.exposureDescription":"Servicios observados, anuncios mDNS y líneas base Web/TLS.","toolbox.compare":"Comparación de instantáneas","toolbox.compareDescription":"Cambios desde la auditoría local anterior.","toolbox.remediation":"Seguimiento de correcciones","toolbox.remediationDescription":"Responsables, prioridades, justificaciones y estados locales.","toolbox.observationLimit":"Observaciones puntuales sin iniciar sesión ni cambiar configuraciones."},
  "pt-BR":{navAssets:"Ativos",navExposure:"Exposição",navCompare:"Comparar",navRemediation:"Correção","toolbox.eyebrow":"Caixa de ferramentas de governança","toolbox.assets":"Inventário de ativos","toolbox.assetsDescription":"Ativos observados, categorias estimadas e contexto da rede local.","toolbox.exposure":"Matriz de exposição de serviços","toolbox.exposureDescription":"Serviços observados, anúncios mDNS e linhas de base Web/TLS.","toolbox.compare":"Comparação de snapshots","toolbox.compareDescription":"Mudanças desde a auditoria local anterior.","toolbox.remediation":"Acompanhamento de correções","toolbox.remediationDescription":"Responsáveis, prioridades, justificativas e estados locais.","toolbox.observationLimit":"Observações pontuais sem login em serviços ou alteração de configuração."},
  it:{navAssets:"Risorse",navExposure:"Esposizione",navCompare:"Confronto",navRemediation:"Correzione","toolbox.eyebrow":"Strumenti di governance","toolbox.assets":"Inventario risorse","toolbox.assetsDescription":"Risorse osservate, categorie stimate e contesto di rete locale.","toolbox.exposure":"Matrice esposizione servizi","toolbox.exposureDescription":"Servizi osservati, annunci mDNS e baseline Web/TLS.","toolbox.compare":"Confronto istantanee","toolbox.compareDescription":"Modifiche dall’audit locale precedente.","toolbox.remediation":"Monitoraggio correzioni","toolbox.remediationDescription":"Responsabili, priorità, motivazioni e stati locali.","toolbox.observationLimit":"Osservazioni puntuali senza accesso ai servizi o modifiche di configurazione."},
  nl:{navAssets:"Assets",navExposure:"Dienstblootstelling",navCompare:"Vergelijken",navRemediation:"Herstel","toolbox.eyebrow":"Governance-gereedschap","toolbox.assets":"Assetinventaris","toolbox.assetsDescription":"Waargenomen assets, categorieschattingen en lokale netwerkcontext.","toolbox.exposure":"Matrix dienstblootstelling","toolbox.exposureDescription":"Waargenomen diensten, mDNS-aankondigingen en Web/TLS-baselines.","toolbox.compare":"Momentopnamen vergelijken","toolbox.compareDescription":"Wijzigingen sinds de vorige lokale audit.","toolbox.remediation":"Herstel volgen","toolbox.remediationDescription":"Lokale eigenaren, prioriteiten, motiveringen en statussen.","toolbox.observationLimit":"Momentopnamen zonder dienstaanmelding of configuratiewijziging."},
};

const remediationOverlays: Partial<Record<Locale, Messages>> = {
  "zh-CN":{"common.error":"错误","common.rawDetail":"原始详情","common.loading":"正在加载…","toolbox.owner":"负责人","toolbox.dueDate":"截止日期","toolbox.status":"状态","toolbox.priority":"优先级","toolbox.businessJustification":"业务理由","toolbox.notes":"备注","toolbox.saveRemediation":"保存整改跟踪","toolbox.remediationSaved":"整改跟踪已保存到本地。","toolbox.noRemediation":"暂无整改记录。","toolbox.remediationLimit":"仅更新本地治理记录，不执行整改命令。","toolbox.statusOpen":"待处理","toolbox.statusAccepted":"已接受风险","toolbox.statusProgress":"处理中","toolbox.statusRemediated":"已整改","toolbox.priorityRoutine":"常规"},
  "zh-TW":{"common.error":"錯誤","common.rawDetail":"原始詳情","common.loading":"正在載入…","toolbox.owner":"負責人","toolbox.dueDate":"截止日期","toolbox.status":"狀態","toolbox.priority":"優先順序","toolbox.businessJustification":"業務理由","toolbox.notes":"備註","toolbox.saveRemediation":"儲存修正追蹤","toolbox.remediationSaved":"修正追蹤已儲存於本機。","toolbox.noRemediation":"暫無修正記錄。","toolbox.remediationLimit":"僅更新本機治理記錄，不執行修正命令。","toolbox.statusOpen":"待處理","toolbox.statusAccepted":"已接受風險","toolbox.statusProgress":"處理中","toolbox.statusRemediated":"已修正","toolbox.priorityRoutine":"例行"},
  ja:{"common.error":"エラー","common.rawDetail":"原文詳細","common.loading":"読み込み中…","toolbox.owner":"担当者","toolbox.dueDate":"期限","toolbox.status":"状態","toolbox.priority":"優先度","toolbox.businessJustification":"業務上の理由","toolbox.notes":"メモ","toolbox.saveRemediation":"是正追跡を保存","toolbox.remediationSaved":"是正追跡をローカルに保存しました。","toolbox.noRemediation":"是正記録はありません。","toolbox.remediationLimit":"ローカルのガバナンス記録のみ更新し、是正コマンドは実行しません。","toolbox.statusOpen":"未対応","toolbox.statusAccepted":"リスク受容","toolbox.statusProgress":"対応中","toolbox.statusRemediated":"是正済み","toolbox.priorityRoutine":"通常"},
  ko:{"common.error":"오류","common.rawDetail":"원문 세부 정보","common.loading":"불러오는 중…","toolbox.owner":"담당자","toolbox.dueDate":"기한","toolbox.status":"상태","toolbox.priority":"우선순위","toolbox.businessJustification":"업무 근거","toolbox.notes":"메모","toolbox.saveRemediation":"개선 추적 저장","toolbox.remediationSaved":"개선 추적을 로컬에 저장했습니다.","toolbox.noRemediation":"개선 기록이 없습니다.","toolbox.remediationLimit":"로컬 거버넌스 기록만 업데이트하며 개선 명령을 실행하지 않습니다.","toolbox.statusOpen":"미처리","toolbox.statusAccepted":"위험 수용","toolbox.statusProgress":"진행 중","toolbox.statusRemediated":"개선 완료","toolbox.priorityRoutine":"일반"},
};

export const toolboxMessages = Object.fromEntries(
  (Object.keys(overlays).concat("en") as Locale[]).map((locale) => [locale, { ...en, ...(overlays[locale] ?? {}), ...(remediationOverlays[locale] ?? {}) }]),
) as Record<Locale, Messages>;
