import type { Locale, Messages } from "./types";

const en: Messages = {
  "common.loading":"Loading…","common.checking":"Checking…","common.required":"Required","common.notProvided":"Not provided","common.open":"Open","common.error":"Error","common.rawDetail":"Raw detail",
  "status.ready":"Ready","status.missing":"Missing","status.warning":"Warning","status.installed":"Installed","status.notInstalled":"Not installed","status.available":"Available","status.unavailable":"Unavailable","status.skipped":"Skipped","status.limited":"Limited","status.success":"Success","status.failed":"Failed","status.running":"Running","status.pending":"Pending","status.unknown":"Unknown",
  "authorization.requiredBeforeEveryRealAudit":"Required before every real audit","authorization.title":"Authorization","authorization.description":"Document the authorized project and confirm every safety boundary.","authorization.projectName":"Project name","authorization.siteOrganization":"Site / organization","authorization.notes":"Notes","authorization.localEngineReadiness":"Local engine readiness","authorization.checkingEngine":"Checking fixed local audit engine…","authorization.engineReady":"Engine","authorization.approvedScriptsReady":"Approved scripts","authorization.nmapReady":"nmap","authorization.latestLabReady":"Latest lab","authorization.confirmAssessNetwork":"I am authorized to assess this network.","authorization.confirmOnlyApprovedScripts":"I understand the audit uses only the thirteen approved local scripts.","authorization.confirmFixedInterface":"I understand the selected local IPv4 audit interface.","authorization.confirmPointInTimeNoConfigChange":"I understand findings are point-in-time observations and no network configuration will be changed.","authorization.confirmAuthorization":"Confirm Authorization","authorization.cancel":"Cancel","authorization.reviewAuthorization":"Review Authorization",
  "engine.localFirstEngine":"Local-first engine","engine.title":"Engine Setup","engine.description":"Install or update the bundled allowlisted audit engine in Application Support.","engine.installed":"Engine installed","engine.scriptReadiness":"Script readiness","engine.nmapAvailability":"nmap availability","engine.latestLabFolder":"Latest lab folder","engine.installedVersion":"Installed version","engine.bundledVersion":"Bundled version","engine.installOrUpdate":"Install or update engine","engine.installing":"Installing…","engine.continueToInterface":"Continue to Interface","engine.openEngineFolder":"Open Engine Folder","engine.applicationSupportPath":"Application Support engine path",
  "interface.eyebrow":"Fixed audit scope","interface.title":"Interface confirmation","interface.description":"Review the authorized context before entering the run page.","interface.project":"Project","interface.siteOrganization":"Site / organization","interface.selectedInterface":"Network interface","interface.executionMode":"Execution mode","interface.continueToRun":"Continue to Run","interface.backToEngine":"Back to Engine Setup",
  "run.eyebrow":"Fixed sequence","run.title":"Run Audit","run.description":"Thirteen approved steps run in order. Stop on Failure is always enabled.","run.runFullAudit":"Run Full Audit","run.stopOnFailure":"Stop on Failure","run.stopDescription":"No later step runs after a failed step.","run.viewReport":"View Report","run.auditLog":"Audit log","run.viewLogs":"View stdout / stderr","run.stdout":"stdout","run.stderr":"stderr","run.durationPending":"Pending","run.authorizationRequiredAgain":"Authorize New Run","run.stepFailedStop":"The audit step failed. Review raw stderr, resolve the local prerequisite, then authorize a new run.",
  "step.initLab":"Initialize lab","step.initLabDescription":"Prepare the local evidence workspace.","step.baseline":"Capture baseline","step.baselineDescription":"Record the selected interface network baseline.","step.passiveAssets":"Passive assets","step.passiveAssetsDescription":"Collect passive asset observations.","step.clientIsolation":"Client isolation","step.clientIsolationDescription":"Check network isolation posture.","step.commonServices":"Common services","step.commonServicesDescription":"Run the approved common-services check.","step.smbPosture":"SMB posture","step.smbPostureDescription":"Assess approved SMB posture signals.","step.gatewayPosture":"Gateway posture","step.gatewayPostureDescription":"Review gateway posture evidence.","step.buildReport":"Build report","step.buildReportDescription":"Generate reports and remediation roadmap.","step.buildFormats":"Build report formats","step.buildFormatsDescription":"Generate static HTML and Excel reports.",
  "report.loading":"Loading latest report…",
  "export.eyebrow":"Local audit artifacts","export.description":"Open the latest evidence workspace or create a timestamped ZIP on the Desktop.","export.latestWorkspace":"Latest audit workspace","export.openLabFolder":"Open Lab Folder","export.openHtml":"Open HTML Report","export.openExcel":"Open Excel Report","export.openedHtml":"Opened HTML report.","export.openedExcel":"Opened Excel report.","export.zipTitle":"Export ZIP","export.exporting":"Exporting…","export.created":"Export ZIP created successfully.","export.openedLab":"Opened latest lab folder.","export.openedFolder":"Opened export folder.",
  "settings.eyebrow":"Local-first configuration","settings.title":"Settings & About","settings.description":"LANPilot Audit keeps audit data on this Mac.","settings.version":"App version","settings.engineVersion":"Engine version","settings.supportedLanguages":"Supported languages","settings.dataStorageLocation":"Data storage","settings.exportFolder":"Export folder","settings.privacyLocalFirst":"Privacy","settings.noCloudUpload":"Local-first, no cloud upload","settings.openEngineFolder":"Open Engine Folder","settings.openExportFolder":"Open Export Folder",
  "language.title":"Language","language.current":"Current language","language.select":"Select language",
  "guardrail.description":"No offensive testing, password attacks, unauthorized login, configuration changes, or lateral movement.",
};

const zhCN: Messages = {
  "common.loading":"正在加载…","common.checking":"正在检查…","common.required":"必需","common.notProvided":"未提供","common.open":"打开","common.error":"错误","common.rawDetail":"原始详情",
  "status.ready":"就绪","status.missing":"缺失","status.warning":"警告","status.installed":"已安装","status.notInstalled":"未安装","status.available":"可用","status.unavailable":"不可用","status.skipped":"已跳过","status.limited":"受限","status.success":"成功","status.failed":"失败","status.running":"运行中","status.pending":"待处理","status.unknown":"未知",
  "authorization.requiredBeforeEveryRealAudit":"每次真实审计前必须完成","authorization.title":"授权确认","authorization.description":"记录已授权项目并确认全部安全边界。","authorization.projectName":"项目名称","authorization.siteOrganization":"站点 / 组织","authorization.notes":"备注","authorization.localEngineReadiness":"本地引擎就绪状态","authorization.checkingEngine":"正在检查固定本地审计引擎…","authorization.engineReady":"引擎","authorization.approvedScriptsReady":"已批准脚本","authorization.nmapReady":"nmap","authorization.latestLabReady":"最近审计目录","authorization.confirmAssessNetwork":"我已获授权评估此网络。","authorization.confirmOnlyApprovedScripts":"我了解审计仅使用十三个已批准的本地脚本。","authorization.confirmFixedInterface":"我了解所选本地 IPv4 审计接口。","authorization.confirmPointInTimeNoConfigChange":"我了解发现结果是时点观察，且不会修改网络配置。","authorization.confirmAuthorization":"确认授权","authorization.cancel":"取消","authorization.reviewAuthorization":"检查授权",
  "engine.localFirstEngine":"本地优先引擎","engine.title":"引擎设置","engine.description":"在 Application Support 中安装或更新内置白名单审计引擎。","engine.installed":"引擎已安装","engine.scriptReadiness":"脚本就绪状态","engine.nmapAvailability":"nmap 可用状态","engine.latestLabFolder":"最近审计目录","engine.installedVersion":"已安装版本","engine.bundledVersion":"内置版本","engine.installOrUpdate":"安装或更新引擎","engine.installing":"正在安装…","engine.continueToInterface":"继续到接口确认","engine.openEngineFolder":"打开引擎目录","engine.applicationSupportPath":"Application Support 引擎路径",
  "interface.eyebrow":"固定审计范围","interface.title":"接口确认","interface.description":"进入运行页面前，请检查已授权的上下文。","interface.project":"项目","interface.siteOrganization":"站点 / 组织","interface.selectedInterface":"网络接口","interface.executionMode":"执行模式","interface.continueToRun":"继续到运行","interface.backToEngine":"返回引擎设置",
  "run.eyebrow":"固定顺序","run.title":"运行审计","run.description":"十三个已批准步骤按顺序运行，并始终在失败时停止。","run.runFullAudit":"运行完整审计","run.stopOnFailure":"失败即停止","run.stopDescription":"任一步骤失败后，不会运行后续步骤。","run.viewReport":"查看报告","run.auditLog":"审计日志","run.viewLogs":"查看 stdout / stderr","run.stdout":"stdout","run.stderr":"stderr","run.durationPending":"待处理","run.authorizationRequiredAgain":"重新授权运行","run.stepFailedStop":"审计步骤失败。请检查原始 stderr，解决本地前置条件后重新授权运行。",
  "step.initLab":"初始化审计目录","step.initLabDescription":"准备本地证据工作区。","step.baseline":"采集基线","step.baselineDescription":"记录所选接口网络基线。","step.passiveAssets":"被动资产","step.passiveAssetsDescription":"收集被动资产观察结果。","step.clientIsolation":"客户端隔离","step.clientIsolationDescription":"检查网络隔离状态。","step.commonServices":"常用服务","step.commonServicesDescription":"运行已批准的常用服务检查。","step.smbPosture":"SMB 状态","step.smbPostureDescription":"评估已批准的 SMB 状态信号。","step.gatewayPosture":"网关状态","step.gatewayPostureDescription":"检查网关状态证据。","step.buildReport":"生成报告","step.buildReportDescription":"生成报告与整改路线图。","step.buildFormats":"生成报告格式","step.buildFormatsDescription":"生成静态 HTML 与 Excel 报告。",
  "report.loading":"正在加载最近报告…",
  "export.eyebrow":"本地审计产物","export.description":"打开最近证据工作区，或在桌面创建带时间戳的 ZIP。","export.latestWorkspace":"最近审计工作区","export.openLabFolder":"打开审计目录","export.openHtml":"打开 HTML 报告","export.openExcel":"打开 Excel 报告","export.openedHtml":"已打开 HTML 报告。","export.openedExcel":"已打开 Excel 报告。","export.zipTitle":"导出 ZIP","export.exporting":"正在导出…","export.created":"已成功创建导出 ZIP。","export.openedLab":"已打开最近审计目录。","export.openedFolder":"已打开导出目录。",
  "settings.eyebrow":"本地优先配置","settings.title":"设置与关于","settings.description":"LANPilot Audit 将审计数据保存在此 Mac 上。","settings.version":"App 版本","settings.engineVersion":"引擎版本","settings.supportedLanguages":"支持的语言","settings.dataStorageLocation":"数据存储位置","settings.exportFolder":"导出目录","settings.privacyLocalFirst":"隐私","settings.noCloudUpload":"本地优先，不上传云端","settings.openEngineFolder":"打开引擎目录","settings.openExportFolder":"打开导出目录",
  "language.title":"语言","language.current":"当前语言","language.select":"选择语言",
  "guardrail.description":"不进行攻击性测试、密码攻击、未授权登录、配置修改或横向移动。",
};

const translated = (values: Partial<Messages>): Messages => {
  const complete = { ...en };
  for (const [key, value] of Object.entries(values)) if (value !== undefined) complete[key] = value;
  return complete;
};
const traditional = (value: string): string => [
  ["审计","稽核"],["网络","網路"],["设置","設定"],["目录","目錄"],["状态","狀態"],["检查","檢查"],["已批准","已核准"],["运行","執行"],["导出","匯出"],["语言","語言"],["证据","證據"],["授权","授權"],["脚本","指令碼"],["客户端","用戶端"],["网关","閘道"],["继续","繼續"],["打开","開啟"],
].reduce((text, [from, to]) => text.split(from).join(to), value);
export const workflowMessages: Record<Locale, Messages> = {
  en,
  "zh-CN": zhCN,
  "zh-TW": translated(Object.fromEntries(Object.entries(zhCN).map(([key, value]) => [key, traditional(value)]))),
  ja: translated({"common.loading":"読み込み中…","common.required":"必須","common.notProvided":"未入力","status.ready":"準備完了","status.missing":"不足","status.warning":"警告","status.notInstalled":"未インストール","status.available":"利用可能","status.unavailable":"利用不可","authorization.requiredBeforeEveryRealAudit":"実際の監査前に毎回必要","authorization.title":"承認確認","authorization.description":"承認済みプロジェクトを記録し、すべての安全境界を確認してください。","authorization.projectName":"プロジェクト名","authorization.siteOrganization":"サイト / 組織","authorization.notes":"メモ","authorization.confirmAuthorization":"承認を確認","authorization.cancel":"キャンセル","authorization.localEngineReadiness":"ローカルエンジンの準備状況","authorization.checkingEngine":"固定ローカル監査エンジンを確認中…","authorization.engineReady":"エンジン","authorization.approvedScriptsReady":"承認済みスクリプト","authorization.latestLabReady":"最新監査フォルダ","authorization.confirmAssessNetwork":"このネットワークを評価する承認を得ています。","authorization.confirmOnlyApprovedScripts":"監査が承認済みの13個のローカルスクリプトのみを使用することを理解しています。","authorization.confirmFixedInterface":"選択したローカル IPv4 監査インターフェース であることを理解しています。","authorization.confirmPointInTimeNoConfigChange":"所見が時点観測であり、ネットワーク設定を変更しないことを理解しています。","authorization.reviewAuthorization":"承認を確認","engine.localFirstEngine":"ローカル優先エンジン","engine.title":"エンジン設定","engine.installOrUpdate":"エンジンをインストールまたは更新","engine.continueToInterface":"インターフェース確認へ進む","engine.description":"Application Support に内蔵の許可リスト監査エンジンをインストールまたは更新します。","engine.installed":"エンジンのインストール","engine.scriptReadiness":"スクリプト準備状況","engine.nmapAvailability":"nmap 利用状況","engine.latestLabFolder":"最新監査フォルダ","engine.installedVersion":"インストール済みバージョン","engine.bundledVersion":"内蔵バージョン","engine.installing":"インストール中…","interface.eyebrow":"固定監査範囲","interface.title":"インターフェース確認","interface.description":"実行ページへ進む前に承認済みコンテキストを確認してください。","interface.project":"プロジェクト","interface.siteOrganization":"サイト / 組織","interface.selectedInterface":"ネットワークインターフェース","interface.executionMode":"実行モード","interface.continueToRun":"実行へ進む","interface.backToEngine":"エンジン設定へ戻る","run.eyebrow":"固定順序","run.title":"監査を実行","run.description":"承認済みの13ステップを順番に実行し、失敗時には必ず停止します。","run.stopDescription":"ステップが失敗した後は後続ステップを実行しません。","run.authorizationRequiredAgain":"新しい実行を承認","run.viewLogs":"stdout / stderr を表示","export.eyebrow":"ローカル監査成果物","settings.eyebrow":"ローカル優先設定","settings.title":"設定と情報","settings.description":"ローカルデータ、バージョン、プライバシー境界を確認します。","guardrail.description":"攻撃的テスト、パスワード攻撃、未承認ログイン、設定変更、横展開は行いません。"}),
  ko: translated({"common.loading":"불러오는 중…","common.required":"필수","common.notProvided":"제공되지 않음","status.ready":"준비됨","status.missing":"누락","status.warning":"경고","status.notInstalled":"설치되지 않음","status.available":"사용 가능","status.unavailable":"사용 불가","authorization.requiredBeforeEveryRealAudit":"모든 실제 감사 전에 필요","authorization.title":"승인 확인","authorization.description":"승인된 프로젝트를 기록하고 모든 안전 경계를 확인하세요.","authorization.projectName":"프로젝트 이름","authorization.siteOrganization":"사이트 / 조직","authorization.notes":"메모","authorization.confirmAuthorization":"승인 확인","authorization.cancel":"취소","authorization.localEngineReadiness":"로컬 엔진 준비 상태","authorization.checkingEngine":"고정 로컬 감사 엔진 확인 중…","authorization.engineReady":"엔진","authorization.approvedScriptsReady":"승인된 스크립트","authorization.latestLabReady":"최신 감사 폴더","authorization.confirmAssessNetwork":"이 네트워크를 평가할 권한이 있습니다.","authorization.confirmOnlyApprovedScripts":"감사가 승인된 13개의 로컬 스크립트만 사용함을 이해합니다.","authorization.confirmFixedInterface":"선택한 로컬 IPv4 감사 인터페이스임을 이해합니다.","authorization.confirmPointInTimeNoConfigChange":"발견 사항은 시점 관찰이며 네트워크 구성을 변경하지 않음을 이해합니다.","authorization.reviewAuthorization":"승인 검토","engine.localFirstEngine":"로컬 우선 엔진","engine.title":"엔진 설정","engine.installOrUpdate":"엔진 설치 또는 업데이트","engine.continueToInterface":"인터페이스 확인으로 계속","engine.description":"Application Support에 포함된 허용 목록 감사 엔진을 설치하거나 업데이트합니다.","engine.installed":"엔진 설치","engine.scriptReadiness":"스크립트 준비 상태","engine.nmapAvailability":"nmap 사용 가능 여부","engine.latestLabFolder":"최신 감사 폴더","engine.installedVersion":"설치된 버전","engine.bundledVersion":"포함된 버전","engine.installing":"설치 중…","interface.eyebrow":"고정 감사 범위","interface.title":"인터페이스 확인","interface.description":"실행 페이지로 이동하기 전에 승인된 컨텍스트를 검토하세요.","interface.project":"프로젝트","interface.siteOrganization":"사이트 / 조직","interface.selectedInterface":"네트워크 인터페이스","interface.executionMode":"실행 모드","interface.continueToRun":"실행으로 계속","interface.backToEngine":"엔진 설정으로 돌아가기","run.eyebrow":"고정 순서","run.title":"감사 실행","run.description":"승인된 13개 단계를 순서대로 실행하며 실패 시 항상 중지합니다.","run.stopDescription":"단계 실패 후에는 후속 단계를 실행하지 않습니다.","run.authorizationRequiredAgain":"새 실행 승인","run.viewLogs":"stdout / stderr 보기","export.eyebrow":"로컬 감사 산출물","settings.eyebrow":"로컬 우선 구성","settings.title":"설정 및 정보","settings.description":"로컬 데이터, 버전 및 개인정보 보호 경계를 확인합니다.","guardrail.description":"공격적 테스트, 암호 공격, 무단 로그인, 구성 변경 또는 수평 이동을 수행하지 않습니다."}),
  de: translated({"status.ready":"Bereit","status.missing":"Fehlt","status.warning":"Warnung","authorization.requiredBeforeEveryRealAudit":"Vor jedem echten Audit erforderlich","authorization.localEngineReadiness":"Bereitschaft der lokalen Engine","authorization.reviewAuthorization":"Autorisierung prüfen","engine.localFirstEngine":"Lokale Engine","engine.description":"Integrierte zugelassene Audit-Engine in Application Support installieren oder aktualisieren.","interface.eyebrow":"Fester Audit-Umfang","run.eyebrow":"Feste Reihenfolge","guardrail.description":"Keine offensiven Tests, Passwortangriffe, unbefugten Anmeldungen, Konfigurationsänderungen oder laterale Bewegung."}),
  fr: translated({"status.ready":"Prêt","status.missing":"Manquant","status.warning":"Avertissement","authorization.requiredBeforeEveryRealAudit":"Requis avant chaque audit réel","authorization.localEngineReadiness":"État du moteur local","authorization.reviewAuthorization":"Vérifier l’autorisation","engine.localFirstEngine":"Moteur local prioritaire","engine.description":"Installer ou mettre à jour le moteur d’audit autorisé intégré dans Application Support.","interface.eyebrow":"Périmètre d’audit fixe","run.eyebrow":"Séquence fixe","guardrail.description":"Aucun test offensif, attaque de mot de passe, connexion non autorisée, modification de configuration ou mouvement latéral."}),
  es: translated({"status.ready":"Listo","status.missing":"Ausente","status.warning":"Advertencia","authorization.requiredBeforeEveryRealAudit":"Obligatorio antes de cada auditoría real","authorization.localEngineReadiness":"Estado del motor local","authorization.reviewAuthorization":"Revisar autorización","engine.localFirstEngine":"Motor local primero","engine.description":"Instalar o actualizar el motor de auditoría permitido incluido en Application Support.","interface.eyebrow":"Alcance fijo de auditoría","run.eyebrow":"Secuencia fija","guardrail.description":"Sin pruebas ofensivas, ataques de contraseña, acceso no autorizado, cambios de configuración ni movimiento lateral."}),
  "pt-BR": translated({"status.ready":"Pronto","status.missing":"Ausente","status.warning":"Aviso","authorization.requiredBeforeEveryRealAudit":"Obrigatório antes de cada auditoria real","authorization.localEngineReadiness":"Prontidão do mecanismo local","authorization.reviewAuthorization":"Revisar autorização","engine.localFirstEngine":"Mecanismo local primeiro","engine.description":"Instalar ou atualizar o mecanismo de auditoria permitido incluído no Application Support.","interface.eyebrow":"Escopo fixo de auditoria","run.eyebrow":"Sequência fixa","guardrail.description":"Sem testes ofensivos, ataques de senha, login não autorizado, alterações de configuração ou movimento lateral."}),
  it: translated({"status.ready":"Pronto","status.missing":"Mancante","status.warning":"Avviso","authorization.requiredBeforeEveryRealAudit":"Obbligatorio prima di ogni audit reale","authorization.localEngineReadiness":"Stato del motore locale","authorization.reviewAuthorization":"Rivedi autorizzazione","engine.localFirstEngine":"Motore locale prioritario","engine.description":"Installare o aggiornare il motore di audit consentito incluso in Application Support.","interface.eyebrow":"Ambito audit fisso","run.eyebrow":"Sequenza fissa","guardrail.description":"Nessun test offensivo, attacco alle password, accesso non autorizzato, modifica della configurazione o movimento laterale."}),
  nl: translated({"status.ready":"Gereed","status.missing":"Ontbreekt","status.warning":"Waarschuwing","authorization.requiredBeforeEveryRealAudit":"Vereist voor elke echte audit","authorization.localEngineReadiness":"Gereedheid lokale engine","authorization.reviewAuthorization":"Autorisatie controleren","engine.localFirstEngine":"Lokale engine eerst","engine.description":"Installeer of werk de ingebouwde toegestane audit-engine bij in Application Support.","interface.eyebrow":"Vast auditbereik","run.eyebrow":"Vaste volgorde","guardrail.description":"Geen offensieve tests, wachtwoordaanvallen, onbevoegde aanmeldingen, configuratiewijzigingen of laterale beweging."}),
};
