import type { Locale, Messages } from "./types";

const en: Messages = {
  "common.loading":"Loading…","common.checking":"Checking…","common.required":"Required","common.notProvided":"Not provided","common.open":"Open","common.error":"Error","common.rawDetail":"Raw detail",
  "status.ready":"Ready","status.missing":"Missing","status.warning":"Warning","status.installed":"Installed","status.notInstalled":"Not installed","status.available":"Available","status.unavailable":"Unavailable","status.skipped":"Skipped","status.limited":"Limited","status.success":"Success","status.failed":"Failed","status.running":"Running","status.pending":"Pending","status.unknown":"Unknown","status.active":"Active","status.stopped":"Stopped","status.detected":"Detected","status.notDetected":"Not detected",
  "navigation.primary":"Primary navigation","navOverview":"Overview","navNetworkCheck":"Network Check","navGovernanceAudit":"Governance Audit","navRun":"Governance Audit","navReport":"Reports","navExport":"Export","navSettings":"Settings","navRemediation":"Remediation",
  "product.tagline":"Local-first network governance and reliability diagnostics","product.localFirst":"Local-first",
  "button.startNetworkCheck":"Start Network Check","button.runGovernanceAudit":"Run Governance Audit","button.viewRawEvidence":"View Raw Evidence","button.exportDiagnosticReport":"Export Diagnostic Report","button.exportSupportBundle":"Export Redacted Support Bundle","button.saveBaseline":"Save Baseline","button.comparePrevious":"Compare Previous Result","button.retest":"Retest",
  "overview.demoNotice":"Showing synthetic demo data until a local network check is run.","overview.currentPath":"Current network path","overview.faultPoint":"Fault point","overview.advice":"Troubleshooting advice","overview.physicalStatus":"Physical network status","overview.dnsStatus":"DNS status","overview.overlayStatus":"Overlay / proxy status","overview.localIp":"Local IP","overview.dhcpDns":"DHCP DNS","overview.gatewayDns":"Gateway DNS query","overview.dnsJudgement":"Judgement","overview.dnsTakenByOverlay":"DNS is currently handled by the overlay or proxy layer.","overview.dnsDirect":"DNS appears to use the local gateway or direct resolver path.",
  "path.physicalInterface":"Physical Interface","path.localGateway":"Local Gateway","path.proxyRules":"Proxy Rules","path.proxyExit":"Proxy Exit","path.internet":"Internet","path.remotePath":"Remote Path","path.overlayUtun":"Overlay utun","path.exitNode":"Exit Node","path.isp":"ISP",
  "latency.title":"Latency visualization","latency.description":"Gateway, DNS, and HTTPS timing shown as simple bars for quick triage.","latency.avg":"avg","latency.min":"min","latency.max":"max","latency.loss":"loss","latency.gatewayDns":"Gateway DNS","latency.systemDns":"System DNS via current path","latency.tcpConnect":"TCP connect","latency.tls":"TLS","latency.ttfb":"TTFB","latency.httpsTotal":"HTTPS total",
  "networkCheck.physicalLan":"Physical LAN","networkCheck.dns":"DNS","networkCheck.overlay":"Overlay / Proxy / VPN","networkCheck.external":"External Internet","networkCheck.judgement":"Fault judgement","networkCheck.evidence":"Evidence","networkCheck.advice":"Advice","networkCheck.physicalHealthy":"Physical LAN is reachable and stable in the current observation.","networkCheck.externalHealthy":"External targets responded within the current baseline window.",
  "authorization.requiredBeforeEveryRealAudit":"Required Before Real Governance Audit","authorization.title":"Authorization","authorization.description":"Document the authorized project and confirm every safety boundary.","authorization.projectName":"Project name","authorization.siteOrganization":"Site / organization","authorization.notes":"Notes","authorization.localEngineReadiness":"Local engine readiness","authorization.checkingEngine":"Checking fixed local audit engine…","authorization.engineReady":"Engine","authorization.approvedScriptsReady":"Allowlisted scripts","authorization.nmapReady":"nmap","authorization.latestLabReady":"Latest lab","authorization.confirmAssessNetwork":"I confirm I am authorized to assess this network.","authorization.confirmOnlyApprovedScripts":"I understand this tool only runs fixed, allowlisted, local low-intensity checks.","authorization.confirmNoOffensiveActions":"I understand it will not perform password guessing, security-abuse modules, repeated login attempts, unauthorized login, or configuration changes.","authorization.confirmFixedInterface":"I understand this check will use the currently selected network interface.","authorization.confirmCurrentInterface":"I confirm this check will use the currently selected network interface.","authorization.confirmPointInTimeNoConfigChange":"I understand findings are point-in-time observations.","authorization.confirmAuthorization":"Confirm Authorization","authorization.cancel":"Cancel","authorization.reviewAuthorization":"Review Authorization",
  "engine.localFirstEngine":"Local-first engine","engine.title":"Engine Setup","engine.description":"Install or update the bundled allowlisted audit engine in Application Support.","engine.installed":"Engine installed","engine.scriptReadiness":"Script readiness","engine.nmapAvailability":"nmap availability","engine.latestLabFolder":"Latest lab folder","engine.installedVersion":"Installed version","engine.bundledVersion":"Bundled version","engine.installOrUpdate":"Install or update engine","engine.installing":"Installing…","engine.continueToInterface":"Continue to Interface","engine.openEngineFolder":"Open Engine Folder","engine.applicationSupportPath":"Application Support engine path",
  "interface.eyebrow":"Network interface selection","interface.title":"Interface confirmation","interface.description":"Select the current authorized physical network interface before running the governance audit.","interface.project":"Project","interface.siteOrganization":"Site / organization","interface.selectedInterface":"Network interface","interface.executionMode":"Execution mode","interface.selectionRule":"Selection rule","interface.preferPhysical":"Auto-select the primary physical interface","interface.selectorTitle":"Network Interface Selector","interface.governanceHint":"Governance Audit defaults to the primary physical interface and does not use overlay interfaces as audit targets.","interface.reliabilityHint":"Network Check can observe overlay interfaces, but keeps the physical path visible for troubleshooting.","interface.autoSelected":"Auto-selected","interface.overlayNotRecommended":"Overlay / not recommended","interface.physicalCandidate":"Physical candidate","interface.notAssociated":"Off or not associated","interface.noIpv4":"No IPv4","interface.noInterfaces":"No eligible local interface was found.","interface.kindOverlay":"Overlay / VPN interface","interface.kindWifi":"Wi-Fi","interface.kindPhysical":"Physical interface","interface.kindBridge":"Bridge interface","interface.kindUnknown":"Unknown interface","interface.continueToRun":"Continue to Run","interface.backToEngine":"Back to Engine Setup",
  "run.eyebrow":"Fixed sequence","run.title":"Run Audit","run.description":"Thirteen approved steps run in order. Stop on Failure is always enabled.","run.runFullAudit":"Run Full Audit","run.stopOnFailure":"Stop on Failure","run.stopDescription":"No later step runs after a failed step.","run.viewReport":"View Report","run.auditLog":"Audit log","run.viewLogs":"View stdout / stderr","run.stdout":"stdout","run.stderr":"stderr","run.durationPending":"Pending","run.authorizationRequiredAgain":"Authorize New Run","run.stepFailedStop":"The audit step failed. Review raw stderr, resolve the local prerequisite, then authorize a new run.",
  "step.initLab":"Initialize lab","step.initLabDescription":"Prepare the local evidence workspace.","step.baseline":"Capture baseline","step.baselineDescription":"Record the selected interface network baseline.","step.passiveAssets":"Passive assets","step.passiveAssetsDescription":"Collect passive asset observations.","step.clientIsolation":"Client isolation","step.clientIsolationDescription":"Check network isolation posture.","step.commonServices":"Common services","step.commonServicesDescription":"Run the approved common-services check.","step.smbPosture":"SMB posture","step.smbPostureDescription":"Assess approved SMB posture signals.","step.gatewayPosture":"Gateway posture","step.gatewayPostureDescription":"Review gateway posture evidence.","step.buildReport":"Build report","step.buildReportDescription":"Generate reports and remediation roadmap.","step.buildFormats":"Build report formats","step.buildFormatsDescription":"Generate static HTML and Excel reports.",
  "report.loading":"Loading latest report…",
  "export.eyebrow":"Local audit artifacts","export.description":"Open the latest evidence workspace or create a timestamped ZIP on the Desktop.","export.latestWorkspace":"Latest audit workspace","export.openLabFolder":"Open Lab Folder","export.openHtml":"Open HTML Report","export.openExcel":"Open Excel Report","export.openedHtml":"Opened HTML report.","export.openedExcel":"Opened Excel report.","export.zipTitle":"Export ZIP","export.exporting":"Exporting…","export.created":"Export ZIP created successfully.","export.openedLab":"Opened latest lab folder.","export.openedFolder":"Opened export folder.",
  "settings.eyebrow":"Local-first configuration","settings.title":"Settings & About","settings.description":"LANPilot Audit keeps audit data on this Mac.","settings.version":"App version","settings.engineVersion":"Engine version","settings.supportedLanguages":"Supported languages","settings.dataStorageLocation":"Data storage","settings.exportFolder":"Export folder","settings.privacyLocalFirst":"Privacy","settings.noCloudUpload":"Local-first, no cloud upload","settings.openEngineFolder":"Open Engine Folder","settings.openExportFolder":"Open Export Folder",
  "language.title":"Language","language.current":"Current language","language.select":"Select language",
  "guardrail.description":"No offensive testing, password attacks, unauthorized login, configuration changes, or lateral movement.",
};

const zhCN: Messages = {
  "common.loading":"正在加载…","common.checking":"正在检查…","common.required":"必需","common.notProvided":"未提供","common.open":"打开","common.error":"错误","common.rawDetail":"原始详情",
  "status.ready":"就绪","status.missing":"缺失","status.warning":"警告","status.installed":"已安装","status.notInstalled":"未安装","status.available":"可用","status.unavailable":"不可用","status.skipped":"已跳过","status.limited":"受限","status.success":"成功","status.failed":"失败","status.running":"运行中","status.pending":"待处理","status.unknown":"未知","status.active":"启用","status.stopped":"已停止","status.detected":"已检测到","status.notDetected":"未检测到",
  "navigation.primary":"主导航","navOverview":"总览","navNetworkCheck":"网络体检","navGovernanceAudit":"治理审计","navRun":"治理审计","navReport":"报告","navExport":"导出","navSettings":"设置","navRemediation":"整改助手",
  "product.tagline":"本地优先的网络治理与可靠性诊断","product.localFirst":"本地优先",
  "button.startNetworkCheck":"开始网络体检","button.runGovernanceAudit":"运行治理审计","button.viewRawEvidence":"查看原始证据","button.exportDiagnosticReport":"导出诊断报告","button.exportSupportBundle":"导出脱敏支持包","button.saveBaseline":"保存基线","button.comparePrevious":"对比上次结果","button.retest":"重新检测",
  "overview.demoNotice":"当前显示合成演示数据；运行本机网络体检后会显示真实结果。","overview.currentPath":"当前网络路径","overview.faultPoint":"故障点","overview.advice":"处理建议","overview.physicalStatus":"物理网络状态","overview.dnsStatus":"DNS 状态","overview.overlayStatus":"Overlay / 代理状态","overview.localIp":"本机 IP","overview.dhcpDns":"DHCP DNS","overview.gatewayDns":"网关 DNS 查询","overview.dnsJudgement":"判断","overview.dnsTakenByOverlay":"DNS 当前由 Overlay 或代理层接管。","overview.dnsDirect":"DNS 当前看起来使用本地网关或直连解析路径。",
  "path.physicalInterface":"物理接口","path.localGateway":"本地网关","path.proxyRules":"代理规则","path.proxyExit":"代理出口","path.internet":"互联网","path.remotePath":"远端路径","path.overlayUtun":"Overlay utun","path.exitNode":"出口节点","path.isp":"运营商路径",
  "latency.title":"延迟可视化","latency.description":"用横向条展示网关、DNS 与 HTTPS 耗时，便于快速定位慢在哪里。","latency.avg":"平均","latency.min":"最小","latency.max":"最大","latency.loss":"丢包","latency.gatewayDns":"网关 DNS","latency.systemDns":"当前路径的系统 DNS","latency.tcpConnect":"TCP 连接","latency.tls":"TLS","latency.ttfb":"首字节","latency.httpsTotal":"HTTPS 总耗时",
  "networkCheck.physicalLan":"物理网络","networkCheck.dns":"DNS","networkCheck.overlay":"Overlay / 代理 / VPN","networkCheck.external":"外部网络","networkCheck.judgement":"故障判断","networkCheck.evidence":"证据","networkCheck.advice":"建议","networkCheck.physicalHealthy":"当前观察中物理网络可达且稳定。","networkCheck.externalHealthy":"外部目标在当前基线窗口内响应正常。",
  "authorization.requiredBeforeEveryRealAudit":"真实治理审计前必须确认","authorization.title":"授权确认","authorization.description":"记录已授权项目并确认全部安全边界。","authorization.projectName":"项目名称","authorization.siteOrganization":"站点 / 组织","authorization.notes":"备注","authorization.localEngineReadiness":"本地引擎状态","authorization.checkingEngine":"正在检查固定本地审计引擎…","authorization.engineReady":"引擎","authorization.approvedScriptsReady":"授权脚本","authorization.nmapReady":"nmap","authorization.latestLabReady":"最新实验目录","authorization.confirmAssessNetwork":"我确认已获得该网络的检测授权","authorization.confirmOnlyApprovedScripts":"我理解本工具只运行固定、白名单、本地低强度检测步骤","authorization.confirmNoOffensiveActions":"我理解不会进行弱口令、漏洞利用、爆破、未授权登录或配置修改","authorization.confirmFixedInterface":"我理解本次检测将使用当前选定的网络接口","authorization.confirmCurrentInterface":"我确认本次检测使用当前选定的网络接口","authorization.confirmPointInTimeNoConfigChange":"我理解检测结果是某一时间点的观察结果","authorization.confirmAuthorization":"确认授权","authorization.cancel":"取消","authorization.reviewAuthorization":"检查授权",
  "engine.localFirstEngine":"本地优先引擎","engine.title":"引擎设置","engine.description":"在 Application Support 中安装或更新内置白名单审计引擎。","engine.installed":"引擎已安装","engine.scriptReadiness":"脚本就绪状态","engine.nmapAvailability":"nmap 可用状态","engine.latestLabFolder":"最近审计目录","engine.installedVersion":"已安装版本","engine.bundledVersion":"内置版本","engine.installOrUpdate":"安装或更新引擎","engine.installing":"正在安装…","engine.continueToInterface":"继续到接口确认","engine.openEngineFolder":"打开引擎目录","engine.applicationSupportPath":"Application Support 引擎路径",
  "interface.eyebrow":"网络接口选择","interface.title":"接口确认","interface.description":"运行治理审计前，请选择当前已授权的物理网络接口。","interface.project":"项目","interface.siteOrganization":"站点 / 组织","interface.selectedInterface":"网络接口","interface.executionMode":"执行模式","interface.selectionRule":"选择规则","interface.preferPhysical":"自动选择主物理接口","interface.selectorTitle":"网络接口选择器","interface.governanceHint":"治理审计默认使用主物理接口，不把 Overlay 接口作为审计目标。","interface.reliabilityHint":"网络体检可以观察 Overlay 接口，但会保留物理路径用于排障。","interface.autoSelected":"自动选择","interface.overlayNotRecommended":"Overlay / 不建议","interface.physicalCandidate":"物理候选","interface.notAssociated":"关闭或未关联","interface.noIpv4":"无 IPv4","interface.noInterfaces":"未发现可用本地接口。","interface.kindOverlay":"Overlay / VPN 接口","interface.kindWifi":"Wi-Fi","interface.kindPhysical":"物理接口","interface.kindBridge":"桥接接口","interface.kindUnknown":"未知接口","interface.continueToRun":"继续到运行","interface.backToEngine":"返回引擎设置",
  "run.eyebrow":"固定顺序","run.title":"运行审计","run.description":"十三个已批准步骤按顺序运行，并始终在失败时停止。","run.runFullAudit":"运行完整审计","run.stopOnFailure":"失败即停止","run.stopDescription":"任一步骤失败后，不会运行后续步骤。","run.viewReport":"查看报告","run.auditLog":"审计日志","run.viewLogs":"查看 stdout / stderr","run.stdout":"stdout","run.stderr":"stderr","run.durationPending":"待处理","run.authorizationRequiredAgain":"重新授权运行","run.stepFailedStop":"审计步骤失败。请检查原始 stderr，解决本地前置条件后重新授权运行。",
  "step.initLab":"初始化审计目录","step.initLabDescription":"准备本地证据工作区。","step.baseline":"采集基线","step.baselineDescription":"记录所选接口网络基线。","step.passiveAssets":"被动资产","step.passiveAssetsDescription":"收集被动资产观察结果。","step.clientIsolation":"客户端隔离","step.clientIsolationDescription":"检查网络隔离状态。","step.commonServices":"常用服务","step.commonServicesDescription":"运行已批准的常用服务检查。","step.smbPosture":"SMB 状态","step.smbPostureDescription":"评估已批准的 SMB 状态信号。","step.gatewayPosture":"网关状态","step.gatewayPostureDescription":"检查网关状态证据。","step.buildReport":"生成报告","step.buildReportDescription":"生成报告与整改路线图。","step.buildFormats":"生成报告格式","step.buildFormatsDescription":"生成静态 HTML 与 Excel 报告。",
  "report.loading":"正在加载最近报告…",
  "export.eyebrow":"本地审计产物","export.description":"打开最近证据工作区，或在桌面创建带时间戳的 ZIP。","export.latestWorkspace":"最近审计工作区","export.openLabFolder":"打开审计目录","export.openHtml":"打开 HTML 报告","export.openExcel":"打开 Excel 报告","export.openedHtml":"已打开 HTML 报告。","export.openedExcel":"已打开 Excel 报告。","export.zipTitle":"导出 ZIP","export.exporting":"正在导出…","export.created":"已成功创建导出 ZIP。","export.openedLab":"已打开最近审计目录。","export.openedFolder":"已打开导出目录。",
  "settings.eyebrow":"本地优先配置","settings.title":"设置与关于","settings.description":"LANPilot Audit 将审计数据保存在此 Mac 上。","settings.version":"App 版本","settings.engineVersion":"引擎版本","settings.supportedLanguages":"支持的语言","settings.dataStorageLocation":"数据存储位置","settings.exportFolder":"导出目录","settings.privacyLocalFirst":"隐私","settings.noCloudUpload":"本地优先，不上传云端","settings.openEngineFolder":"打开引擎目录","settings.openExportFolder":"打开导出目录",
  "language.title":"语言","language.current":"当前语言","language.select":"选择语言",
  "guardrail.description":"不进行攻击性测试、密码攻击、未授权登录、配置修改或横向移动。",
};

const translated = (values: Partial<Messages>): Messages => {
  const complete = { ...en };
  for (const [key, value] of Object.entries(values)) if (value !== undefined) complete[key] = value;
  return complete;
};
const traditional = (value: string): string => [
  ["审计","稽核"],["网络","網路"],["设置","設定"],["目录","目錄"],["状态","狀態"],["检查","檢查"],["体检","體檢"],["已批准","已核准"],["运行","執行"],["导出","匯出"],["语言","語言"],["证据","證據"],["授权","授權"],["脚本","指令碼"],["客户端","用戶端"],["网关","閘道"],["继续","繼續"],["打开","開啟"],["优先","優先"],["处理","處理"],["检测","檢測"],["互联网","網際網路"],["运营商","營運商"],["当前","目前"],["结果","結果"],
].reduce((text, [from, to]) => text.split(from).join(to), value);
export const workflowMessages: Record<Locale, Messages> = {
  en,
  "zh-CN": zhCN,
  "zh-TW": translated(Object.fromEntries(Object.entries(zhCN).map(([key, value]) => [key, traditional(value)]))),
  ja: translated({"common.loading":"読み込み中…","common.required":"必須","common.notProvided":"未入力","status.ready":"準備完了","status.missing":"不足","status.warning":"警告","status.notInstalled":"未インストール","status.available":"利用可能","status.unavailable":"利用不可","authorization.requiredBeforeEveryRealAudit":"実際の監査前に毎回必要","authorization.title":"承認確認","authorization.description":"承認済みプロジェクトを記録し、すべての安全境界を確認してください。","authorization.projectName":"プロジェクト名","authorization.siteOrganization":"サイト / 組織","authorization.notes":"メモ","authorization.confirmAuthorization":"承認を確認","authorization.cancel":"キャンセル","authorization.localEngineReadiness":"ローカルエンジンの準備状況","authorization.checkingEngine":"固定ローカル監査エンジンを確認中…","authorization.engineReady":"エンジン","authorization.approvedScriptsReady":"承認済みスクリプト","authorization.latestLabReady":"最新監査フォルダ","authorization.confirmAssessNetwork":"このネットワークを評価する承認を得ています。","authorization.confirmOnlyApprovedScripts":"監査が承認済みの13個のローカルスクリプトのみを使用することを理解しています。","authorization.confirmFixedInterface":"選択したローカル IPv4 監査インターフェース であることを理解しています。","authorization.confirmPointInTimeNoConfigChange":"所見が時点観測であり、ネットワーク設定を変更しないことを理解しています。","authorization.reviewAuthorization":"承認を確認","engine.localFirstEngine":"ローカル優先エンジン","engine.title":"エンジン設定","engine.installOrUpdate":"エンジンをインストールまたは更新","engine.continueToInterface":"インターフェース確認へ進む","engine.description":"Application Support に内蔵の許可リスト監査エンジンをインストールまたは更新します。","engine.installed":"エンジンのインストール","engine.scriptReadiness":"スクリプト準備状況","engine.nmapAvailability":"nmap 利用状況","engine.latestLabFolder":"最新監査フォルダ","engine.installedVersion":"インストール済みバージョン","engine.bundledVersion":"内蔵バージョン","engine.installing":"インストール中…","interface.eyebrow":"固定監査範囲","interface.title":"インターフェース確認","interface.description":"実行ページへ進む前に承認済みコンテキストを確認してください。","interface.project":"プロジェクト","interface.siteOrganization":"サイト / 組織","interface.selectedInterface":"ネットワークインターフェース","interface.executionMode":"実行モード","interface.continueToRun":"実行へ進む","interface.backToEngine":"エンジン設定へ戻る","run.eyebrow":"固定順序","run.title":"監査を実行","run.description":"承認済みの13ステップを順番に実行し、失敗時には必ず停止します。","run.stopDescription":"ステップが失敗した後は後続ステップを実行しません。","run.authorizationRequiredAgain":"新しい実行を承認","run.viewLogs":"stdout / stderr を表示","export.eyebrow":"ローカル監査成果物","settings.eyebrow":"ローカル優先設定","settings.title":"設定と情報","settings.description":"ローカルデータ、バージョン、プライバシー境界を確認します。","guardrail.description":"攻撃的テスト、パスワード攻撃、未承認ログイン、設定変更、横展開は行いません。"}),
  ko: translated({"common.loading":"불러오는 중…","common.required":"필수","common.notProvided":"제공되지 않음","status.ready":"준비됨","status.missing":"누락","status.warning":"경고","status.notInstalled":"설치되지 않음","status.available":"사용 가능","status.unavailable":"사용 불가","authorization.requiredBeforeEveryRealAudit":"모든 실제 감사 전에 필요","authorization.title":"승인 확인","authorization.description":"승인된 프로젝트를 기록하고 모든 안전 경계를 확인하세요.","authorization.projectName":"프로젝트 이름","authorization.siteOrganization":"사이트 / 조직","authorization.notes":"메모","authorization.confirmAuthorization":"승인 확인","authorization.cancel":"취소","authorization.localEngineReadiness":"로컬 엔진 준비 상태","authorization.checkingEngine":"고정 로컬 감사 엔진 확인 중…","authorization.engineReady":"엔진","authorization.approvedScriptsReady":"승인된 스크립트","authorization.latestLabReady":"최신 감사 폴더","authorization.confirmAssessNetwork":"이 네트워크를 평가할 권한이 있습니다.","authorization.confirmOnlyApprovedScripts":"감사가 승인된 13개의 로컬 스크립트만 사용함을 이해합니다.","authorization.confirmFixedInterface":"선택한 로컬 IPv4 감사 인터페이스임을 이해합니다.","authorization.confirmPointInTimeNoConfigChange":"발견 사항은 시점 관찰이며 네트워크 구성을 변경하지 않음을 이해합니다.","authorization.reviewAuthorization":"승인 검토","engine.localFirstEngine":"로컬 우선 엔진","engine.title":"엔진 설정","engine.installOrUpdate":"엔진 설치 또는 업데이트","engine.continueToInterface":"인터페이스 확인으로 계속","engine.description":"Application Support에 포함된 허용 목록 감사 엔진을 설치하거나 업데이트합니다.","engine.installed":"엔진 설치","engine.scriptReadiness":"스크립트 준비 상태","engine.nmapAvailability":"nmap 사용 가능 여부","engine.latestLabFolder":"최신 감사 폴더","engine.installedVersion":"설치된 버전","engine.bundledVersion":"포함된 버전","engine.installing":"설치 중…","interface.eyebrow":"고정 감사 범위","interface.title":"인터페이스 확인","interface.description":"실행 페이지로 이동하기 전에 승인된 컨텍스트를 검토하세요.","interface.project":"프로젝트","interface.siteOrganization":"사이트 / 조직","interface.selectedInterface":"네트워크 인터페이스","interface.executionMode":"실행 모드","interface.continueToRun":"실행으로 계속","interface.backToEngine":"엔진 설정으로 돌아가기","run.eyebrow":"고정 순서","run.title":"감사 실행","run.description":"승인된 13개 단계를 순서대로 실행하며 실패 시 항상 중지합니다.","run.stopDescription":"단계 실패 후에는 후속 단계를 실행하지 않습니다.","run.authorizationRequiredAgain":"새 실행 승인","run.viewLogs":"stdout / stderr 보기","export.eyebrow":"로컬 감사 산출물","settings.eyebrow":"로컬 우선 구성","settings.title":"설정 및 정보","settings.description":"로컬 데이터, 버전 및 개인정보 보호 경계를 확인합니다.","guardrail.description":"공격적 테스트, 암호 공격, 무단 로그인, 구성 변경 또는 수평 이동을 수행하지 않습니다."}),
  de: translated({"status.ready":"Bereit","status.missing":"Fehlt","status.warning":"Warnung","authorization.requiredBeforeEveryRealAudit":"Vor jedem echten Audit erforderlich","authorization.localEngineReadiness":"Bereitschaft der lokalen Engine","authorization.reviewAuthorization":"Autorisierung prüfen","engine.localFirstEngine":"Lokale Engine","engine.description":"Integrierte zugelassene Audit-Engine in Application Support installieren oder aktualisieren.","interface.eyebrow":"Fester Audit-Umfang","run.eyebrow":"Feste Reihenfolge","guardrail.description":"Keine offensiven Tests, Passwortangriffe, unbefugten Anmeldungen, Konfigurationsänderungen oder laterale Bewegung."}),
  fr: translated({"status.ready":"Prêt","status.missing":"Manquant","status.warning":"Avertissement","authorization.requiredBeforeEveryRealAudit":"Requis avant chaque audit réel","authorization.localEngineReadiness":"État du moteur local","authorization.reviewAuthorization":"Vérifier l’autorisation","engine.localFirstEngine":"Moteur local prioritaire","engine.description":"Installer ou mettre à jour le moteur d’audit autorisé intégré dans Application Support.","interface.eyebrow":"Périmètre d’audit fixe","run.eyebrow":"Séquence fixe","guardrail.description":"Aucun test offensif, attaque de mot de passe, connexion non autorisée, modification de configuration ou mouvement latéral."}),
  es: translated({"status.ready":"Listo","status.missing":"Ausente","status.warning":"Advertencia","authorization.requiredBeforeEveryRealAudit":"Obligatorio antes de cada auditoría real","authorization.localEngineReadiness":"Estado del motor local","authorization.reviewAuthorization":"Revisar autorización","engine.localFirstEngine":"Motor local primero","engine.description":"Instalar o actualizar el motor de auditoría permitido incluido en Application Support.","interface.eyebrow":"Alcance fijo de auditoría","run.eyebrow":"Secuencia fija","guardrail.description":"Sin pruebas ofensivas, ataques de contraseña, acceso no autorizado, cambios de configuración ni movimiento lateral."}),
  "pt-BR": translated({"status.ready":"Pronto","status.missing":"Ausente","status.warning":"Aviso","authorization.requiredBeforeEveryRealAudit":"Obrigatório antes de cada auditoria real","authorization.localEngineReadiness":"Prontidão do mecanismo local","authorization.reviewAuthorization":"Revisar autorização","engine.localFirstEngine":"Mecanismo local primeiro","engine.description":"Instalar ou atualizar o mecanismo de auditoria permitido incluído no Application Support.","interface.eyebrow":"Escopo fixo de auditoria","run.eyebrow":"Sequência fixa","guardrail.description":"Sem testes ofensivos, ataques de senha, login não autorizado, alterações de configuração ou movimento lateral."}),
  it: translated({"status.ready":"Pronto","status.missing":"Mancante","status.warning":"Avviso","authorization.requiredBeforeEveryRealAudit":"Obbligatorio prima di ogni audit reale","authorization.localEngineReadiness":"Stato del motore locale","authorization.reviewAuthorization":"Rivedi autorizzazione","engine.localFirstEngine":"Motore locale prioritario","engine.description":"Installare o aggiornare il motore di audit consentito incluso in Application Support.","interface.eyebrow":"Ambito audit fisso","run.eyebrow":"Sequenza fissa","guardrail.description":"Nessun test offensivo, attacco alle password, accesso non autorizzato, modifica della configurazione o movimento laterale."}),
  nl: translated({"status.ready":"Gereed","status.missing":"Ontbreekt","status.warning":"Waarschuwing","authorization.requiredBeforeEveryRealAudit":"Vereist voor elke echte audit","authorization.localEngineReadiness":"Gereedheid lokale engine","authorization.reviewAuthorization":"Autorisatie controleren","engine.localFirstEngine":"Lokale engine eerst","engine.description":"Installeer of werk de ingebouwde toegestane audit-engine bij in Application Support.","interface.eyebrow":"Vast auditbereik","run.eyebrow":"Vaste volgorde","guardrail.description":"Geen offensieve tests, wachtwoordaanvallen, onbevoegde aanmeldingen, configuratiewijzigingen of laterale beweging."}),
};

const productUiMessages: Record<Locale, Messages> = {
  en: {},
  "zh-CN": {},
  "zh-TW": {},
  ja: {
    "navigation.primary": "主要ナビゲーション", navOverview: "概要", navNetworkCheck: "ネットワークチェック", navGovernanceAudit: "ガバナンス監査", navRun: "ガバナンス監査", navReport: "レポート", navExport: "エクスポート", navSettings: "設定", navRemediation: "是正支援",
    "product.tagline": "ローカル優先のネットワークガバナンスと信頼性診断", "product.localFirst": "ローカル優先",
    "button.startNetworkCheck": "ネットワークチェックを開始", "button.runGovernanceAudit": "ガバナンス監査を実行", "button.viewRawEvidence": "原文証拠を表示", "button.exportDiagnosticReport": "診断レポートをエクスポート", "button.exportSupportBundle": "マスク済みサポートパックをエクスポート", "button.saveBaseline": "ベースラインを保存", "button.comparePrevious": "前回結果と比較", "button.retest": "再チェック",
    "overview.demoNotice": "ローカルチェックを実行するまで合成デモデータを表示しています。", "overview.currentPath": "現在のネットワーク経路", "overview.faultPoint": "故障箇所", "overview.advice": "対処案", "overview.physicalStatus": "物理ネットワーク状態", "overview.dnsStatus": "DNS 状態", "overview.overlayStatus": "Overlay / プロキシ状態", "overview.localIp": "ローカル IP", "overview.dhcpDns": "DHCP DNS", "overview.gatewayDns": "ゲートウェイ DNS 照会", "overview.dnsJudgement": "判断", "overview.dnsTakenByOverlay": "DNS は Overlay またはプロキシ層で処理されています。", "overview.dnsDirect": "DNS はローカルゲートウェイまたは直接リゾルバ経路を使用しているようです。",
    "path.physicalInterface": "物理インターフェース", "path.localGateway": "ローカルゲートウェイ", "path.proxyRules": "プロキシルール", "path.proxyExit": "プロキシ出口", "path.internet": "インターネット", "path.remotePath": "リモート経路", "path.overlayUtun": "Overlay utun", "path.exitNode": "出口ノード", "path.isp": "ISP 経路",
    "latency.title": "遅延の可視化", "latency.description": "ゲートウェイ、DNS、HTTPS の所要時間をバーで表示します。", "latency.avg": "平均", "latency.min": "最小", "latency.max": "最大", "latency.loss": "損失", "latency.gatewayDns": "ゲートウェイ DNS", "latency.systemDns": "現在経路のシステム DNS", "latency.tcpConnect": "TCP 接続", "latency.tls": "TLS", "latency.ttfb": "TTFB", "latency.httpsTotal": "HTTPS 合計",
    "networkCheck.physicalLan": "物理 LAN", "networkCheck.dns": "DNS", "networkCheck.overlay": "Overlay / プロキシ / VPN", "networkCheck.external": "外部インターネット", "networkCheck.judgement": "故障判断", "networkCheck.evidence": "証拠", "networkCheck.advice": "助言", "networkCheck.physicalHealthy": "現在の観測では物理 LAN は到達可能で安定しています。", "networkCheck.externalHealthy": "外部ターゲットは現在の基準内で応答しています。",
    "authorization.confirmNoOffensiveActions": "弱いパスワード確認、脆弱性利用、総当たり、未承認ログイン、設定変更を行わないことを理解しています。", "authorization.confirmCurrentInterface": "現在選択中のネットワークインターフェースを使用することを確認します。",
    "interface.selectionRule": "選択ルール", "interface.preferPhysical": "主要な物理インターフェースを自動選択", "interface.selectorTitle": "ネットワークインターフェース選択", "interface.governanceHint": "ガバナンス監査は主要な物理インターフェースを既定で使用し、Overlay を監査対象にしません。", "interface.reliabilityHint": "ネットワークチェックは Overlay を観測できますが、物理経路も表示します。", "interface.autoSelected": "自動選択", "interface.overlayNotRecommended": "Overlay / 非推奨", "interface.physicalCandidate": "物理候補", "interface.notAssociated": "オフまたは未接続", "interface.noIpv4": "IPv4 なし", "interface.noInterfaces": "利用可能なローカルインターフェースが見つかりません。", "interface.kindOverlay": "Overlay / VPN インターフェース", "interface.kindWifi": "Wi-Fi", "interface.kindPhysical": "物理インターフェース", "interface.kindBridge": "ブリッジインターフェース", "interface.kindUnknown": "不明なインターフェース",
  },
  ko: {
    "navigation.primary": "기본 탐색", navOverview: "개요", navNetworkCheck: "네트워크 점검", navGovernanceAudit: "거버넌스 감사", navRun: "거버넌스 감사", navReport: "보고서", navExport: "내보내기", navSettings: "설정", navRemediation: "개선 도우미",
    "product.tagline": "로컬 우선 네트워크 거버넌스 및 안정성 진단", "product.localFirst": "로컬 우선",
    "button.startNetworkCheck": "네트워크 점검 시작", "button.runGovernanceAudit": "거버넌스 감사 실행", "button.viewRawEvidence": "원본 근거 보기", "button.exportDiagnosticReport": "진단 보고서 내보내기", "button.exportSupportBundle": "마스킹된 지원 묶음 내보내기", "button.saveBaseline": "기준선 저장", "button.comparePrevious": "이전 결과 비교", "button.retest": "다시 점검",
    "overview.demoNotice": "로컬 네트워크 점검을 실행할 때까지 합성 데모 데이터를 표시합니다.", "overview.currentPath": "현재 네트워크 경로", "overview.faultPoint": "문제 지점", "overview.advice": "처리 조언", "overview.physicalStatus": "물리 네트워크 상태", "overview.dnsStatus": "DNS 상태", "overview.overlayStatus": "Overlay / 프록시 상태", "overview.localIp": "로컬 IP", "overview.dhcpDns": "DHCP DNS", "overview.gatewayDns": "게이트웨이 DNS 질의", "overview.dnsJudgement": "판단", "overview.dnsTakenByOverlay": "DNS가 현재 Overlay 또는 프록시 계층에서 처리됩니다.", "overview.dnsDirect": "DNS가 로컬 게이트웨이 또는 직접 해석 경로를 사용하는 것으로 보입니다.",
    "path.physicalInterface": "물리 인터페이스", "path.localGateway": "로컬 게이트웨이", "path.proxyRules": "프록시 규칙", "path.proxyExit": "프록시 출구", "path.internet": "인터넷", "path.remotePath": "원격 경로", "path.overlayUtun": "Overlay utun", "path.exitNode": "출구 노드", "path.isp": "ISP 경로",
    "latency.title": "지연 시간 시각화", "latency.description": "게이트웨이, DNS, HTTPS 시간을 막대로 표시합니다.", "latency.avg": "평균", "latency.min": "최소", "latency.max": "최대", "latency.loss": "손실", "latency.gatewayDns": "게이트웨이 DNS", "latency.systemDns": "현재 경로의 시스템 DNS", "latency.tcpConnect": "TCP 연결", "latency.tls": "TLS", "latency.ttfb": "TTFB", "latency.httpsTotal": "HTTPS 합계",
    "networkCheck.physicalLan": "물리 LAN", "networkCheck.dns": "DNS", "networkCheck.overlay": "Overlay / 프록시 / VPN", "networkCheck.external": "외부 인터넷", "networkCheck.judgement": "문제 판단", "networkCheck.evidence": "근거", "networkCheck.advice": "조언", "networkCheck.physicalHealthy": "현재 관찰에서 물리 LAN은 도달 가능하고 안정적입니다.", "networkCheck.externalHealthy": "외부 대상이 현재 기준 범위 내에서 응답했습니다.",
    "authorization.confirmNoOffensiveActions": "약한 암호 확인, 취약점 이용, 무차별 대입, 무단 로그인 또는 구성 변경을 수행하지 않음을 이해합니다.", "authorization.confirmCurrentInterface": "현재 선택된 네트워크 인터페이스를 사용함을 확인합니다.",
    "interface.selectionRule": "선택 규칙", "interface.preferPhysical": "주 물리 인터페이스 자동 선택", "interface.selectorTitle": "네트워크 인터페이스 선택기", "interface.governanceHint": "거버넌스 감사는 기본적으로 주 물리 인터페이스를 사용하며 Overlay를 감사 대상으로 사용하지 않습니다.", "interface.reliabilityHint": "네트워크 점검은 Overlay를 관찰할 수 있지만 물리 경로도 함께 표시합니다.", "interface.autoSelected": "자동 선택", "interface.overlayNotRecommended": "Overlay / 권장하지 않음", "interface.physicalCandidate": "물리 후보", "interface.notAssociated": "꺼짐 또는 연결 안 됨", "interface.noIpv4": "IPv4 없음", "interface.noInterfaces": "사용 가능한 로컬 인터페이스를 찾지 못했습니다.", "interface.kindOverlay": "Overlay / VPN 인터페이스", "interface.kindWifi": "Wi-Fi", "interface.kindPhysical": "물리 인터페이스", "interface.kindBridge": "브리지 인터페이스", "interface.kindUnknown": "알 수 없는 인터페이스",
  },
  de: { navOverview:"Übersicht", navNetworkCheck:"Netzwerkprüfung", navGovernanceAudit:"Governance-Audit", navRun:"Governance-Audit", navReport:"Berichte", navExport:"Export", navSettings:"Einstellungen", navRemediation:"Maßnahmen", "product.tagline":"Lokale Netzwerk-Governance und Zuverlässigkeitsdiagnose", "product.localFirst":"Lokal zuerst", "button.startNetworkCheck":"Netzwerkprüfung starten", "button.runGovernanceAudit":"Governance-Audit starten", "overview.demoNotice":"Bis zur lokalen Prüfung werden synthetische Demodaten angezeigt.", "overview.currentPath":"Aktueller Netzwerkpfad", "overview.faultPoint":"Fehlerstelle", "overview.advice":"Hinweise", "networkCheck.physicalLan":"Physisches LAN", "networkCheck.dns":"DNS", "networkCheck.overlay":"Overlay / Proxy / VPN", "networkCheck.external":"Externes Internet", "interface.selectorTitle":"Netzwerkschnittstelle auswählen" },
  fr: { navOverview:"Vue d’ensemble", navNetworkCheck:"Vérification réseau", navGovernanceAudit:"Audit de gouvernance", navRun:"Audit de gouvernance", navReport:"Rapports", navExport:"Exporter", navSettings:"Réglages", navRemediation:"Remédiation", "product.tagline":"Diagnostics locaux de gouvernance et de fiabilité réseau", "product.localFirst":"Local d’abord", "button.startNetworkCheck":"Démarrer la vérification réseau", "button.runGovernanceAudit":"Lancer l’audit de gouvernance", "overview.demoNotice":"Des données de démonstration synthétiques sont affichées jusqu’à une vérification locale.", "overview.currentPath":"Chemin réseau actuel", "overview.faultPoint":"Point de défaillance", "overview.advice":"Conseils", "networkCheck.physicalLan":"LAN physique", "networkCheck.dns":"DNS", "networkCheck.overlay":"Overlay / proxy / VPN", "networkCheck.external":"Internet externe", "interface.selectorTitle":"Sélecteur d’interface réseau" },
  es: { navOverview:"Resumen", navNetworkCheck:"Comprobación de red", navGovernanceAudit:"Auditoría de gobernanza", navRun:"Auditoría de gobernanza", navReport:"Informes", navExport:"Exportar", navSettings:"Ajustes", navRemediation:"Remediación", "product.tagline":"Diagnóstico local de gobernanza y fiabilidad de red", "product.localFirst":"Local primero", "button.startNetworkCheck":"Iniciar comprobación de red", "button.runGovernanceAudit":"Ejecutar auditoría de gobernanza", "overview.demoNotice":"Se muestran datos sintéticos de demo hasta ejecutar una comprobación local.", "overview.currentPath":"Ruta de red actual", "overview.faultPoint":"Punto de fallo", "overview.advice":"Consejos", "networkCheck.physicalLan":"LAN física", "networkCheck.dns":"DNS", "networkCheck.overlay":"Overlay / proxy / VPN", "networkCheck.external":"Internet externo", "interface.selectorTitle":"Selector de interfaz de red" },
  "pt-BR": { navOverview:"Visão geral", navNetworkCheck:"Verificação de rede", navGovernanceAudit:"Auditoria de governança", navRun:"Auditoria de governança", navReport:"Relatórios", navExport:"Exportar", navSettings:"Configurações", navRemediation:"Remediação", "product.tagline":"Diagnóstico local de governança e confiabilidade de rede", "product.localFirst":"Local primeiro", "button.startNetworkCheck":"Iniciar verificação de rede", "button.runGovernanceAudit":"Executar auditoria de governança", "overview.demoNotice":"Dados sintéticos de demonstração aparecem até uma verificação local ser executada.", "overview.currentPath":"Caminho de rede atual", "overview.faultPoint":"Ponto de falha", "overview.advice":"Orientações", "networkCheck.physicalLan":"LAN física", "networkCheck.dns":"DNS", "networkCheck.overlay":"Overlay / proxy / VPN", "networkCheck.external":"Internet externa", "interface.selectorTitle":"Seletor de interface de rede" },
  it: { navOverview:"Panoramica", navNetworkCheck:"Verifica rete", navGovernanceAudit:"Audit di governance", navRun:"Audit di governance", navReport:"Rapporti", navExport:"Esporta", navSettings:"Impostazioni", navRemediation:"Rimedio", "product.tagline":"Diagnostica locale di governance e affidabilità rete", "product.localFirst":"Locale prima", "button.startNetworkCheck":"Avvia verifica rete", "button.runGovernanceAudit":"Esegui audit di governance", "overview.demoNotice":"Sono mostrati dati demo sintetici finché non viene eseguita una verifica locale.", "overview.currentPath":"Percorso rete attuale", "overview.faultPoint":"Punto di guasto", "overview.advice":"Consigli", "networkCheck.physicalLan":"LAN fisica", "networkCheck.dns":"DNS", "networkCheck.overlay":"Overlay / proxy / VPN", "networkCheck.external":"Internet esterno", "interface.selectorTitle":"Selettore interfaccia di rete" },
  nl: { navOverview:"Overzicht", navNetworkCheck:"Netwerkcontrole", navGovernanceAudit:"Governance-audit", navRun:"Governance-audit", navReport:"Rapporten", navExport:"Exporteren", navSettings:"Instellingen", navRemediation:"Remediatie", "product.tagline":"Lokale netwerkgovernance en betrouwbaarheidsdiagnostiek", "product.localFirst":"Lokaal eerst", "button.startNetworkCheck":"Netwerkcontrole starten", "button.runGovernanceAudit":"Governance-audit uitvoeren", "overview.demoNotice":"Synthetische demogegevens worden getoond tot een lokale controle is uitgevoerd.", "overview.currentPath":"Huidig netwerkpad", "overview.faultPoint":"Foutpunt", "overview.advice":"Advies", "networkCheck.physicalLan":"Fysieke LAN", "networkCheck.dns":"DNS", "networkCheck.overlay":"Overlay / proxy / VPN", "networkCheck.external":"Extern internet", "interface.selectorTitle":"Netwerkinterface kiezen" },
};

for (const locale of Object.keys(productUiMessages) as Locale[]) {
  Object.assign(workflowMessages[locale], productUiMessages[locale]);
}
