import {
  diagnoseNetworkReliability,
  type NetworkReliabilityEvidence,
} from "./network-reliability";

export const demoStashTunHealthyLan: NetworkReliabilityEvidence = {
  profile: "VPN / Proxy Active",
  generatedAt: "2026-06-19T00:00:00+08:00",
  physicalLan: {
    activeInterface: "en5",
    interfaceKind: "usb_ethernet",
    ipv4: "192.0.2.24",
    subnetMask: "255.255.255.0",
    dhcpOk: true,
    dhcpServer: "192.0.2.1",
    dhcpRouter: "192.0.2.1",
    dhcpDns: ["192.0.2.1"],
    gatewayIp: "192.0.2.1",
    gatewayPingLossPct: 0,
    gatewayPingAvgMs: 2.4,
    gatewayPingJitterMs: 0.8,
    gatewayDnsMs: 5,
    gatewayDnsTimedOut: false,
    arpSummary: "4 ARP neighbor rows observed",
    selfAssignedAddress: false,
    multipleActiveInterfaces: true,
  },
  localControlPlane: {
    systemDnsServers: ["1.0.0.1", "198.51.100.53"],
    scopedResolvers: ["utun15"],
    resolverSummary: "System DNS is currently scoped through utun15.",
    mdnsSummary: "mDNS observation is available after a governance audit.",
    listeningServices: [],
  },
  overlay: {
    defaultRouteInterface: "utun15",
    defaultRouteGateway: "198.18.0.1",
    utunInterfaces: ["utun15"],
    hasProxyRange19818: true,
    hasTailscaleRange10064: false,
    hasTailscaleDns100100: false,
    hasTailscaleIpv6Dns: false,
    tailscaleRunning: false,
    tailscaleExitNode: false,
    tailscaleDnsEnabled: false,
    stashDetected: true,
    stashTunDetected: true,
    stashPorts: [7890, 9090],
    clashDetected: false,
    surgeDetected: false,
    wireGuardDetected: false,
    openVpnDetected: false,
    multipleOverlayComponents: false,
    dnsViaOverlay: true,
  },
  external: {
    publicIp: "203.0.113.45",
    publicIpOrg: "Demo Proxy Exit",
    publicIpLocation: "Demo Region",
    targets: [
      { group: "developer", url: "https://github.com", dnsMs: 220, tcpConnectMs: 380, tlsMs: 520, ttfbMs: 820, totalMs: 2400, status: 200, remoteIp: "203.0.113.80", failed: false },
      { group: "apple", url: "https://www.apple.com", dnsMs: 5, tcpConnectMs: 120, tlsMs: 180, ttfbMs: 260, totalMs: 780, status: 200, remoteIp: "203.0.113.81", failed: false },
    ],
  },
  rawEvidenceRefs: ["demo-network-environment-evidence.json"],
};

export const demoTailscaleExitNodeSlow: NetworkReliabilityEvidence = {
  ...demoStashTunHealthyLan,
  profile: "Tailscale Remote Access",
  physicalLan: {
    ...demoStashTunHealthyLan.physicalLan,
    activeInterface: "en0",
    interfaceKind: "wifi",
    ipv4: "198.51.100.24",
    gatewayIp: "198.51.100.1",
    dhcpRouter: "198.51.100.1",
    dhcpDns: ["198.51.100.1"],
    gatewayPingAvgMs: 8,
    gatewayPingJitterMs: 2,
    gatewayDnsMs: 18,
  },
  localControlPlane: {
    ...demoStashTunHealthyLan.localControlPlane,
    systemDnsServers: ["100.100.100.100"],
    scopedResolvers: ["utun8"],
    resolverSummary: "Tailscale DNS is active.",
  },
  overlay: {
    defaultRouteInterface: "utun8",
    defaultRouteGateway: null,
    utunInterfaces: ["utun8"],
    hasProxyRange19818: false,
    hasTailscaleRange10064: true,
    hasTailscaleDns100100: true,
    hasTailscaleIpv6Dns: false,
    tailscaleRunning: true,
    tailscaleExitNode: true,
    tailscaleDnsEnabled: true,
    stashDetected: false,
    stashTunDetected: false,
    stashPorts: [],
    clashDetected: false,
    surgeDetected: false,
    wireGuardDetected: false,
    openVpnDetected: false,
    multipleOverlayComponents: false,
    dnsViaOverlay: true,
  },
  external: {
    publicIp: "203.0.113.88",
    publicIpOrg: "Demo Cloud Exit Node",
    publicIpLocation: "Demo Remote Region",
    targets: [
      { group: "developer", url: "https://github.com", dnsMs: 320, tcpConnectMs: 900, tlsMs: 1200, ttfbMs: 1800, totalMs: 5200, status: 200, remoteIp: "203.0.113.90", failed: false },
    ],
  },
};

export const demoGatewayPacketLoss: NetworkReliabilityEvidence = {
  ...demoStashTunHealthyLan,
  profile: "Physical LAN Issue",
  physicalLan: {
    ...demoStashTunHealthyLan.physicalLan,
    activeInterface: "en5",
    interfaceKind: "usb_ethernet",
    gatewayPingLossPct: 12,
    gatewayPingAvgMs: 85,
    gatewayPingJitterMs: 30,
    gatewayDnsMs: 180,
  },
  localControlPlane: {
    ...demoStashTunHealthyLan.localControlPlane,
    systemDnsServers: ["192.0.2.1"],
    scopedResolvers: [],
    resolverSummary: "Gateway DNS is used directly.",
  },
  overlay: {
    defaultRouteInterface: "en5",
    defaultRouteGateway: "192.0.2.1",
    utunInterfaces: [],
    hasProxyRange19818: false,
    hasTailscaleRange10064: false,
    hasTailscaleDns100100: false,
    hasTailscaleIpv6Dns: false,
    tailscaleRunning: false,
    tailscaleExitNode: false,
    tailscaleDnsEnabled: false,
    stashDetected: false,
    stashTunDetected: false,
    stashPorts: [],
    clashDetected: false,
    surgeDetected: false,
    wireGuardDetected: false,
    openVpnDetected: false,
    multipleOverlayComponents: false,
    dnsViaOverlay: false,
  },
  external: {
    publicIp: null,
    publicIpOrg: null,
    publicIpLocation: null,
    targets: [
      { group: "apple", url: "https://www.apple.com", dnsMs: 180, tcpConnectMs: 1200, tlsMs: 1600, ttfbMs: 2400, totalMs: 6400, status: null, failed: true },
    ],
  },
};

const demoSummary = diagnoseNetworkReliability(demoStashTunHealthyLan);

export const demoNetworkReliabilityRun = {
  summary: demoSummary,
  evidence: demoStashTunHealthyLan,
  reportMarkdown: "# LANPilot Audit demo network check",
  supportBundlePath: "/Users/demo/lanpilot-demo/08-network-reliability/network-environment-redacted-support-bundle.zip",
  outputDirectory: "/Users/demo/lanpilot-demo/08-network-reliability",
};
